sync_to_github:
  image: alpine/git
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
  script:
    - git remote add github git@github.com:あなたのユーザー名/freshalert.git || true
    - git push github HEAD:main --force
  only:
    - main