name: freshalert
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^14.2.7

  # State Management
  provider: ^6.1.2

  # Camera and ML
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.13.0

  # UI Components
  material_design_icons_flutter: ^7.0.7296

  # Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3

  # Image Handling
  image_picker: ^1.0.4

  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0

  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
