// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFN8xdJaGTsoCjkKvBaxx8yfV2lS0v9yE',
    appId: '1:68522821159:web:8d130df0bc622674ef3002',
    messagingSenderId: '68522821159',
    projectId: 'freshalert-a93ae',
    authDomain: 'freshalert-a93ae.firebaseapp.com',
    storageBucket: 'freshalert-a93ae.firebasestorage.app',
    measurementId: 'G-C2C5LJGW1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCISxtF47CiwoxZOxLSjDlmqlj2LEoxyY8',
    appId: '1:68522821159:android:676a50511a0949b6ef3002',
    messagingSenderId: '68522821159',
    projectId: 'freshalert-a93ae',
    storageBucket: 'freshalert-a93ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfXDzx2eb0ylRZEshKk-DtCmfJ6umE_Us',
    appId: '1:68522821159:ios:c7ad81d89477d772ef3002',
    messagingSenderId: '68522821159',
    projectId: 'freshalert-a93ae',
    storageBucket: 'freshalert-a93ae.firebasestorage.app',
    iosBundleId: 'com.example.freshalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfXDzx2eb0ylRZEshKk-DtCmfJ6umE_Us',
    appId: '1:68522821159:ios:c7ad81d89477d772ef3002',
    messagingSenderId: '68522821159',
    projectId: 'freshalert-a93ae',
    storageBucket: 'freshalert-a93ae.firebasestorage.app',
    iosBundleId: 'com.example.freshalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFN8xdJaGTsoCjkKvBaxx8yfV2lS0v9yE',
    appId: '1:68522821159:web:a9f8bcd5166e1201ef3002',
    messagingSenderId: '68522821159',
    projectId: 'freshalert-a93ae',
    authDomain: 'freshalert-a93ae.firebaseapp.com',
    storageBucket: 'freshalert-a93ae.firebasestorage.app',
    measurementId: 'G-Y2G2633YFY',
  );
}
